### ISSUE TITLE
Unfollow who not follow back not working

### ISSUE THREAD

**Issue by Brahim-Brd** [officialputuid/toolsig#46]
![Screenshot_20211016-012956_Termux](https://user-images.githubusercontent.com/77865773/137566879-dbccb23d-4509-4b2f-920d-cec26c80a588.jpg)
Was working totally fine, used to unfollow more than 400 users and than it began failing with the last 110 users
Did the basic method of using this tool: 
- Git clone ....
- cd toolsig
- npm i
- node index.js
     -unfollow not follow back
            -typed username
            -    //    password
And all of this was leading to the shown error, a little help will be really appreciated.

**Comment by officialputuid** [comment]
You use 4000ms (4 seconds) delay, because of that it's worse than robots, use your mind, instagram detects it, your account will be banned if you use delay too fast, recommended delay is above 5 minutes++, and it looks like not using bots . do not use tools if your account is shadow banned (1-2 weeks)
